{% set name = "shogun" %}

{% set version = "6.1.4" %}
{% set commit = 'shogun_' + version %}
{% set sha256 = "d618a6c6fa6c230608bda7a17585387b89d11d58085a9457cbfba0c438a08969" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/shogun-toolbox/shogun/archive/{{ commit }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      # https://github.com/shogun-toolbox/shogun/issues/4068
      - libpython-linking.patch
      # https://github.com/shogun-toolbox/shogun/pull/4637
      - swig-4-fix.patch

{% set lc, vs, ve, prefix, parbuild = "\\", "$", "", "$PREFIX", "-j $CPU_COUNT" %}  # [unix]
{% set lc, vs, ve, prefix, parbuild = "^", "%", "%", "%LIBRARY_PREFIX%", "" %}      # [win]
build:
  number: 0
  skip: true  # [win32 or win]
  script: |
    mkdir build
    cd build

    # figure out include / library paths
    # https://github.com/conda/conda-build/issues/2130 will be proper solution
    pyinc=$($PYTHON -c "from distutils import sysconfig; print(sysconfig.get_python_inc())")                           # [unix]
    pylib=$(otool -L $PYTHON | grep 'libpython.*\.dylib' | tr '\t' ' ' | cut -d' ' -f2 | sed "s|@rpath|$PREFIX/lib|")  # [osx]
    pylib=$(ldd $PYTHON | grep $PREFIX | grep 'libpython.*\.so' | cut -d' ' -f3)                                       # [linux]

    cmake ..                                      {{ lc }}
        -G"{{vs}}CMAKE_GENERATOR{{ve}}"           {{ lc }}
        -DCMAKE_PREFIX_PATH="{{ prefix }}"        {{ lc }}
        -DCMAKE_INSTALL_PREFIX="{{ prefix }}"     {{ lc }}
        -DCMAKE_BUILD_TYPE=Release                {{ lc }}
        -DBUILD_EXAMPLES=OFF                      {{ lc }}
        -DBUILD_META_EXAMPLES=OFF                 {{ lc }}
        -DENABLE_TESTING=OFF                      {{ lc }}
        -DENABLE_COVERAGE=OFF                     {{ lc }}
        -DPYTHON_EXECUTABLE={{vs}}PYTHON{{ve}}    {{ lc }}
        -DPYTHON_INCLUDE_DIR=$pyinc               \  # [unix]
        -DPYTHON_LIBRARIES=$pylib                 \  # [unix]
        -DLIBSHOGUN=OFF                           {{ lc }}
        -DINTERFACE_PYTHON=ON
    if errorlevel 1 exit 1  # [win]

    cmake --build . --target _interface_python --config Release -- {{ parbuild }}
    if errorlevel 1 exit 1  # [win]

    cmake --build . --target install --config Release -- {{ parbuild }}
    if errorlevel 1 exit 1  # [win]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake 3.15
    - swig
  host:
    - python
    - setuptools
    - numpy
    - shogun-cpp {{ version }}
    - arpack       # [not win]
    - bzip2
    - ctags
    - curl
    - eigen
    - glpk
    - hdf5
    - json-c
    - libxml2
    - lzo
    - libprotobuf
    - rxcpp 4.1.0
    - snappy
    - xz
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('shogun-cpp', max_pin='x.x.x') }}
    - ctags
    - glpk
    - json-c
    - snappy

test:
  imports:
    - shogun
  commands:
    - conda inspect linkages -p $PREFIX shogun  # [not win]
    - conda inspect objects -p $PREFIX shogun   # [osx]

about:
  home: http://shogun.ml
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Unified and efficient Machine Learning'
  description: |
    The Shogun Machine learning toolbox offers a wide range of efficient and
    unified Machine Learning methods.
  doc_url: http://shogun.ml/examples/latest/index.html
  dev_url: https://github.com/shogun-toolbox/shogun/wiki

extra:
  recipe-maintainers:
    - djsutherland
    - vigsterkr
