appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jD/jUDQXHUlRBYfclCw6UablEmVPMj093djLThlrvVepQ0ubvNOz79iid73gPafIHMA6pkJhyUYd1BcPN4+7P4dH2aEMqmrjP3s8okcSBqqoXk0Z8gVMN+XCcAjALCIJ65L+gC6G1YKH0gizzxO9lxBQs0ZAmi2cRkOJkh3LBotpDVfhHJ05xGaIAD6pn4loKqz0TbRvOhTwbmkt2AKk/EsypNy9q7a1WKZVFI6cZLcfGc0sCLnYj3BiaGucmFPBv/WeRv0OdP/NuW3B7kU7wVJLTkPomFmzB0SR40HBEGgRJhF1YAZ81NJTN5Bbd31xUYQqKfwwCsqSpQOkjmzik11aJ73gyA+0OQOZAOF1F93DkIfVqZVRt1PGZQJECgWsbBaw81jXCz+ZvAS+98ohyEGMMDrz+KB0yySv2sh9JSGMAsxiH62fntn4IfqbVp1d47b+4lkqxo4SGGCa0I/ER/HLPldEAInNLoBoBOw5w31dh7R7WWuxQHIEYRwbRQsToxA85VmUn2YYAAZ0jD5Ly//KJuG1UGJV4Z/NvjFECMopHoaQCuS835U6PaZqYhQHEXJH2dAKBMdZWT/4lbSPnFf7sActMUeefYV3eNhEVz6Zlc/eI2tbD1xJnllqYn/yJQuFevc2yaKTFD/07rQ2ebZgcriOSfkGl0hIm8Vwekg=}
